# Generated by Django 4.0.3 on 2022-04-14 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ClientSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Client Session Name')),
            ],
            options={
                'verbose_name': 'Client Session',
                'verbose_name_plural': 'Client Sessions',
            },
        ),
        migrations.CreateModel(
            name='UpdateState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pts', models.IntegerField(verbose_name='pts')),
                ('qts', models.IntegerField(verbose_name='qts')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('seq', models.IntegerField(verbose_name='seq')),
                (
                    'client_session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='django_telethon.clientsession',
                        verbose_name='Client Session',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Update state',
                'verbose_name_plural': 'Update states',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_key', models.BinaryField(editable=True, verbose_name='Auth Key')),
                ('data_center_id', models.IntegerField(db_index=True, verbose_name='Data Center ID')),
                ('port', models.IntegerField(verbose_name='Port')),
                ('server_address', models.CharField(max_length=255, verbose_name='Server Address')),
                ('takeout_id', models.BigIntegerField(null=True, verbose_name='Takeout ID')),
                (
                    'client_session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='django_telethon.clientsession',
                        verbose_name='Client Session',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_value', models.BigIntegerField(verbose_name='Hash Value')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                (
                    'client_session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='django_telethon.clientsession',
                        verbose_name='Client Session',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
            },
        ),
        migrations.CreateModel(
            name='SentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5_digest', models.BinaryField(verbose_name='MD5 digest')),
                ('file_size', models.IntegerField(verbose_name='File size')),
                ('file_type', models.IntegerField(choices=[(0, 'Document'), (1, 'Photo')], verbose_name='Type')),
                ('hash_value', models.BigIntegerField(verbose_name='Hash value')),
                ('file_id', models.IntegerField(verbose_name='File ID')),
                (
                    'client_session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='django_telethon.clientsession',
                        verbose_name='Client Session',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Sent file',
                'verbose_name_plural': 'Sent files',
                'unique_together': {('client_session', 'md5_digest', 'file_size', 'file_type')},
            },
        ),
    ]
