# Generated by Django 5.0.3 on 2024-12-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('django_telethon', '0002_updatestate_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatestate',
            name='entity_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='updatestate',
            unique_together={('client_session', 'entity_id')},
        ),
    ]
