# Generated by Django 6.0.6 on 2026-07-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('django_telethon', '0003_alter_updatestate_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentfile',
            name='file_id',
            field=models.BigIntegerField(verbose_name='File ID'),
        ),
    ]
